### ISSUE TITLE
name 'FT1' is not defined

### ISSUE THREAD

**Issue by t-anton** [i-shah/hts-db#1]
Hi,

In the last cell "FT1" is not defined.

`NameError: name 'FT1' is not defined` 

Thank you,

Todor

**Comment by i-shah** [comment]
FT1=['p53Act','DNADamage','StressKinase','OxidativeStress','MicrotubuleCSK','LysosomalMass',
     'MitoMass','MitoMembPot','MitoFxnI','Steatosis',
     'MitoticArrest','CellCycleArrest','NuclearSize','DNATexture','Apoptosis','CellLoss']

Updated now in the notebook
